theme: jekyll-theme-minimal
url: https://608.lib.wtf
title: IST 608 - Fall 2022

instructor:
  name: Logan Rath, PhD
  title: Adjunct instructor
  email: lrath@brockport.edu

course_description: This class is designed to introduce you to the logic of research methods and the major methods used to conduct academic research. Throughout this semester, we will explore many facets of this topic, including the process of research, how to conduct a literature review and develop an addressable research question, quantitative and qualitative methods, descriptive and inferential statistics through correlation and regression, and the creation of grant or research proposals.

# Build Settings
markdown: kramdown
